### ISSUE TITLE
Use custom formatter

### ISSUE THREAD

**Issue by martinpengellyphillips** [4degrees/lucidity#1]
The use of Python string.format with Bunch is a bit of a hack and can lead to some weird behaviour as well as requiring an additional dependency. 

Add a custom formatter that follows the Lucidity format rules exactly (nested dot syntax for item access) and remove the dependency on Bunch.

**Comment by BigRoy** [comment]
Here's a custom formatter that passes all tests in the package and allows you to remove the dependency on Bunch.

```python
import string

class Formatter(string.Formatter):
    def get_field(self, field_name, args, kwargs):
        ''' Given a `field_name`, find the object it references.

        This is an exact copy of the implementation of ``string.Formatter.get_field`` except that it uses dictionary
        access when the object is a dictionary.
        '''
        first, rest = field_name._formatter_field_name_split()

        obj = self.get_value(first, args, kwargs)

        # loop through the rest of the field_name, doing
        #  getattr or getitem as needed
        for is_attr, i in rest:
            if isinstance(obj, dict):   # when the object is a dictionary use dictionary access
                obj = obj[i]
            elif is_attr:
                obj = getattr(obj, i)
            else:
                obj = obj[i]

        return obj, first
```

For an example implementation see the latest commit to my fork of **lucidity**: [Implement custom formatter, remove dependency to Bunch](https://github.com/BigRoy/lucidity/commit/55b54fa2c6b570773b97f57adc34462cd9147309)

**Comment by martinpengellyphillips** [comment]
Thanks for the bump. I went for a simpler approach as Lucidity doesn't use any of the advanced formatting features at all at present. 

I'll be merging #12 tomorrow, but feel free to shout if I have missed something here.
