### ISSUE TITLE
Template references in templates

### ISSUE THREAD

**Issue by martinpengellyphillips** [4degrees/lucidity#2]
Would it be possible to have templates "mixin" other templates to aid managing common placeholders? For example:

```python
Template('job_path', '/jobs/{job}')
Template('shot_path', '{$job_path}/shots/{shot}')
```

Here the `{$job_path}` in the *shot_path* template pattern would be expanded to the value specified by the template with name *job_path*.

Would need to work for both parsing and formatting.

**Comment by jordibares** [comment]
That would be most useful.

**Comment by martinpengellyphillips** [comment]
This requires each Template to have a way to look up other templates. Two possible options:

a) Only implement for the higher level `lucidity.format` and `lucidity.parse` functions that already require a list of other template objects to work with.

b) Each Template accepts a `template_lookup` callback on construction that is used to lookup another template at runtime. In addition to this, could introduce a default registry (global `TEMPLATES` variable) throughout the framework for those that want simplicity over configurability.

**Comment by mkolar** [comment]
This would be a lovely and very welcome feature.

**Comment by BigRoy** [comment]
>> b) Each Template accepts a template_lookup callback on construction that is used to lookup another template at runtime. In addition to this, could introduce a default registry (global TEMPLATES variable) throughout the framework for those that want simplicity over configurability.

I think option *B* would keep the logic in a single Template simple. Only during construction will it use the lookup to expand those variables. At the same time this means logic for *parse* and *format* can stay the same and have no need to be recursive.

For example
```python

a = Template('job_path', '/jobs/{job}')

template_lookup = [a]
b = Template('shot_path', '{$job_path}/shots/{shot}', template_lookup=template_lookup)
print b.pattern
# /jobs/{job}/shots/{shot}
```

**Comment by martinpengellyphillips** [comment]
> This does make it required to have the lookup templates to be defined before the others.
I feel this might be too much of a restriction.

**Comment by BigRoy** [comment]
> I feel this might be too much of a restriction.

I agree. This would make it too cumbersome to manage, especially when loading from other schema that represent the set of templates in an unsorted dictionary (eg. YAML #20). 

Otherwise I'd opt for an implementation of something like a Schema class so its easier to manage all the accessible templates. A global lookup might interfere if one would have multiple representations of templates?

A thing to note though is that we'd also have to take care of possible infinite recursion (referencing back & forth), for example:

```python
a = Template('job', '/jobs/@brief')
b = Template('art', '@job/art')
c = Template('brief', '@art/brief')
```

**Comment by martinpengellyphillips** [comment]
Yeah, I'm starting to lean towards a collection class, though it brings with it some interesting issues (when and how references get resolved, can a template belong to more than one collection etc.)

Regarding cyclic references - I guess it would be appropriate for Lucidity to just error at runtime when they are detected unless someone can think of a compelling use case for cyclic reference support?

**Comment by martinpengellyphillips** [comment]
Ok, here's what I am thinking. `Template.parse` and `Template.format` get an additional `template_resolver` argument. If supplied the resolver should support a `get` method for retrieving a template by name (so works with plain dict). A `TemplateCollection` class then automatically passes that argument as itself when you call `TemplateCollection.parse`, `TemplateCollection.format` etc.

This has the benefit of a template retaining its individuality (can exist in multiple collections) whilst providing a simple way for collection classes to provide convenience. The only downside is passing as an argument is slightly odd in that it is rare you would ever want to pass a different resolver for `format` vs `parse`, but I can live with that. 

I'll start coding this up soon, but please chime in with any thoughts or point out any issues with this approach I might have missed.

**Comment by BigRoy** [comment]
> Ok, here's what I am thinking. Template.parse and Template.format get an additional template_resolver argument. If supplied the resolver should support a get method for retrieving a template by name (so works with plain dict). A TemplateCollection class then automatically passes that argument as itself when you call TemplateCollection.parse, TemplateCollection.format etc.

> This has the benefit of a template retaining its individuality (can exist in multiple collections) whilst providing a simple way for collection classes to provide convenience. The only downside is passing as an argument is slightly odd in that it is rare you would ever want to pass a different resolver for format vs parse, but I can live with that. 

Sounds good to me. Did a quick draft by changing Schema to a dict in my repo. All that's missing is the parsing/formatting on the template with referenced templates.

**Comment by martinpengellyphillips** [comment]
What should happen for `Template.keys()` method?

1. Return placeholders with raw references. E.g. `('@job_path', 'shot')`
2. Expand references and return all keys that compose pattern at that time. E.g. `('job', 'shot')`

**Comment by BigRoy** [comment]
Maybe it should return all expanded keys by default and have a parameter like `expand_references`. Maybe even another for `expand_depth`?
I wouldn't return the reference name among keys (the referenced template might not even have any keys!). I would give the Template a `references` property to get the referenced Templates.
What do you think?

-------- Oorspronkelijk bericht --------
Van: Martin Pengelly-Phillips <notifications@github.com>
Datum: 31-05-2015  1:08 PM  (GMT+01:00)
Aan: 4degrees/lucidity <lucidity@noreply.github.com>
Cc: Roy Nieterau <roy_nieterau@hotmail.com>
Onderwerp: Re: [lucidity] Template references in templates (#2)

What should happen for `Template.keys()` method?

1. Return placeholders with raw references. E.g. `('@job_path', 'shot')`
2. Expand references and return all keys that compose pattern at that time. E.g. `('job', 'shot')`

---

**Comment by BigRoy** [comment]
> What should happen for Template.keys() method?

Maybe it should return all expanded keys by default and have a parameter like `expand_references`. Maybe even another for `expand_depth`?

I wouldn't return the reference name among keys (the referenced template might not even have any keys!). To get the references I would give the Template a `references` property returning the referenced Templates. *Note: this should probably be a method instead of a property since you need to pass it the `resolve_templates`.*

What do you think?

**Comment by martinpengellyphillips** [comment]
Yeah, a `Template.references` method makes sense. Seems like more and more methods will need resolver passed to them. Might need to rethink approach of passing resolver to each method at runtime. Could rely on `TemplateCollection` making a copy of templates passed to it so it can set an independant resolver. Alternatively have a proxy that wraps the Template and does the resolving before calling the proxied methods.

Will have a play and see how it all feels.

**Comment by martinpengellyphillips** [comment]
I've started this on branch *2_template_references_in_templates*. Just need to write documentation now, but feel free to take a look and comment.

**Comment by BigRoy** [comment]
> I've started this on branch 2_template_references_in_templates. Just need to write documentation now, but feel free to take a look and comment.

Had a quick go with this and it instantly passed the tests I already had in place for referenced templates and the YAML implementation.

At this stage the template_resolver attribute is assigned to the template only on initialization. Maybe it should also have a function like `set_template_resolver()` so it's clear that one can easily override the Resolver for the template at any time. (Works fine with the YAML test). 

Currently I'm doing this in my Schema (which you are referring to as a *TemplateCollection*):
```python
    class Schema(dict):
        def add_template(self, template):
            assert isinstance(template, lucidity.Template)
            template.template_resolver = self
            self[template.name] = template
```

**Comment by martinpengellyphillips** [comment]
> At this stage the template_resolver attribute is assigned to the template only on initialization. Maybe it should also have a function like set_template_resolver() so it's clear that one can easily override the Resolver for the template at any time.

As `Template.template_resolver` is a public property I don't see any issue with folks just setting it as you do in your example. No need for a separate setter method like `set_template_resolver()`. Could make it clearer in the docstring that it can be changed at any time though I guess.

**Comment by martinpengellyphillips** [comment]
Pull request #24 up. Will merge soon.

**Comment by BigRoy** [comment]
> As Template.template_resolver is a public property I don't see any issue with folks just setting it as you do in your example.

Definitely. Just have a habit to stay away from changing public attributes since it's not always safe to change public attributes. Good to see this is fine here.

> Could make it clearer in the docstring that it can be changed at any time though I guess.

I think that would help either way.
