### ISSUE TITLE
Keys of arbitrary amount of folders (nesting) in Templates

### ISSUE THREAD

**Issue by BigRoy** [4degrees/lucidity#21]
Is it possible to have a key in a template represent more than a single folder, and possibly even allow to match an arbitrary amount of folders?

### Goal

Allow a single key to represent multiple folders (like a set of folders). 

For example:

```python
template = Template("{root}/model/{parents}/{asset}")
```

Where `{parents}` could possibly be:

- `character/hero`
- `prop/supermarket`

Maybe we can set up a way to describe how much folders it may hold:

```python
template = Template("{root}/model/{parents:folders(0,*)}/{asset}")
```

In the format of:
`{xxx:folders(a,b)}`

Where *a* and *b* are respectively min/max?

### Future

With this we could extend of lucidity even further to allow custom regex patterns to be implemented by users. (Which this basically also is, a customized regex).

We could have a look at *jinja2* templating that also allow custom function calls to be implemented in the templates.

**Comment by martinpengellyphillips** [comment]
Are you proposing something different to the existing custom regex support? http://lucidity.readthedocs.org/en/latest/guide/tutorial.html#per-placeholder

**Comment by BigRoy** [comment]
Actually I totally missed that! That's actually very neat!

Since you're using the colon to implement custom regex. 
Does that mean that standard formatting techniques are not possible?

```python
>>> print "{0:03d}".format(4)  # python >= 2.6
>>> 004
```

**Comment by martinpengellyphillips** [comment]
That's correct. I couldn't resolve in my head a nice way to support custom formatting and custom pattern matching without it getting confusing for the developer. I figured it is trivial to preformat the *data* before passing to the template for formatting into the template spec.

**Comment by BigRoy** [comment]
Isn't it better to maybe use a different separator for the custom regex so it doesn't interfere with the built-in formatting support?

```python
# standard python formatting using ':'
a = Template("a/b/c/{value:04d}")

# custom regex using '~'
b = Template("a/b/c/{value~[\w]+")

# calling a registered method
c = Template("a/b/c/{value[folder(0, 5)]}
```

The registered method could be using a function to define a regex pattern, to possibly simplify the template definitions? Again, this could all be overkill?

**Comment by martinpengellyphillips** [comment]
I'm wary of overcomplicating it or it becoming a full blown templating language - *look it can do HTML!* ;-)

I did consider this when starting out though and whilst I am happy with the decision that additional formatting of data occurs elsewhere I would love to be able to solve the problem here in a good way.

The issue I see with even supporting general Python formatting is the ambiguity/complexity in behaviour.

Consider your example:
```python
a = Template("a/b/c/{value:04d}")
```
It seemed to me reasonable that in this case the caller would assume that some magic would also take place to make `04d` part of the parse logic (i.e. only parse 4 padded digits) rather than having to do:
```python
a = Template("a/b/c/{value~\d\{4\}:04d}")
```
I'm open to solutions / proposals though!

**Comment by BigRoy** [comment]
> It seemed to me reasonable that in this case the caller would assume that some magic would also take place to make 04d part of the parse logic (i.e. only parse 4 padded digits) ...

That is totally True. That would mean any of the formatting methods would be accompanied by a parsing method. It easily becomes too complex to manage.

**Comment by BigRoy** [comment]
Any reason why this might not work:

```python
path = 'C:/projects/foobar/dev/animation/001_personalized/sh010_actionShot/maya'
template = lucidity.Template('anim', r'animation/{parent_hierarchy:((?:(?<=[\\\\/])[^\\\\/]+[\\\\/]?)+)}/maya')
print template.parse(path)
```

Even though the pattern does match:

```python
import re
path = 'C:/projects/foobar/dev/animation/001_personalized/sh010_actionShot/maya'
print re.findall(r'animation/((?:(?<=[\\\\/])[^\\\\/]+[\\\\/]?)+)/maya', path)
```

**Comment by martinpengellyphillips** [comment]
It is due to [anchoring](http://lucidity.readthedocs.org/en/latest/guide/tutorial.html#anchoring).

By default the pattern for a template is anchored at the start, so as your candidate *path* does not start with 'animation/' it does not match.

The following would change the anchoring and then would work:

```python
>>> template = lucidity.Template(
...     'anim', 
...     r'animation/{parent_hierarchy:((?:(?<=[\\\\/])[^\\\\/]+[\\\\/]?)+)}/maya', 
...     anchor=lucidity.Template.ANCHOR_END
... )
>>> template.parse(path)
{'parent_hierarchy': '001_personalized/sh010_actionShot'}
```

**Comment by BigRoy** [comment]
A derp, yes!

How does that actually work with referenced templates #2 ? 
I assume the anchor of the top most template is used, correct?
(And is that documented somewhere?)

**Comment by martinpengellyphillips** [comment]
Correct, the top most anchor is used. I'll add that to the docs for #2 before merging.
